const iconMap = {
  "Crafts": "brush",
  "Dance & Theatre":"theaters",
  "Entertainment": "movie",
  "Arts & Culture": "brush",
  "Film":"movie",
  "Literature":"book",
  "Museums & Exhibits":"museum",
  "Music":"music_note",
  "Photography":"camera_alt",
  "Beauty & Fashion":"checkroom",
  "Business & Industry":"business",
  "Attractions & Local":"local_activity",
  "Live Shows":"mic",
  "Nightlife":"local_bar",
  "Pop Culture":"whatshot",
  "Shopping":"shopping_cart",
  "Baseball":"sports_baseball",
  "Basketball":"sports_basketball",
  "Cycling":"directions_bike",
  "Fighting & Martial Arts":"sports_mma",
  "Fitness":"fitness_center",
  "Football":"sports_football",
  "Golf":"sports_golf",
  "Other":"add",
  "Running & Walking":"directions_run",
  "Soccer":"sports_soccer",
  "Swimming & Waterpolo":"pool",
  "Tennis":"sports_tennis",
  "Yoga":"self_improvement",
  "Family & Children":"family_restroom",
  "Food & Drink":"fastfood",
  "Health & Medicine":"health_and_safety",
  "Animals & Pets":"pets",
  "Charity & Non-Profit":"foundation",
  "LGBT":"looks",
  "Politics":"flag",
  "Religion & Spirituality":"",
  "Science & Technology":"science",
}

export {
  iconMap
}